# Starship configuration

[python]
# Only show the module when inside a Python virtual environment
detect_extensions = ['py', 'ipynb', 'pyc', 'pyd', 'pyo', 'pyw', 'pyz']
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']
detect_folders = []
# Show venv name when activated
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = 'üêç '
style = 'yellow bold'
pyenv_version_name = false
python_binary = ['python', 'python3', 'python2']

[character]
success_symbol = '[‚ûú](bold green)'
error_symbol = '[‚ûú](bold red)'

[directory]
truncation_length = 3
truncation_symbol = '‚Ä¶/'

[git_branch]
symbol = 'üå± '
format = '[$symbol$branch]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[hostname]
ssh_only = true
format = '[$hostname](bold blue) '

[username]
show_always = false
format = '[$user]($style) in '
